<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- WEBISTE THEME -->
    <link rel="stylesheet" href="assets/css/theme.css">
    <title>Erreur 404</title>
</head>

<body>
    <section class="section-error">
        <div class="text-center box-container">
            <h1>Erreur 404 - Page non trouvée</h1>
            <?php if (\Libraries\Session::getError('404') !== null) : ?>
                <p class="alert alert-danger" role="alert">
                    <?= \Libraries\Session::getError('404') ?>
                </p>
                <?php \Libraries\Session::destroyByValue('error-404') ?>

            <?php endif; ?>
            <a href="index.php?page=home" class="cancel">Retourner vers l'accueil</a>
        </div>
    </section>
</body>

</html>