<section class="section-contact">
    <h1>Contactez-nous</h1>

    <div class="container">
        <?php \Libraries\Error::display('error-contact') ?>

        <?php if (isset($_GET['success']) && $_GET['success'] === 'true') : ?>
            <div class="success box-container">
                <p>Votre message a bien été envoyé !</p>
                <a href="index.php?page=contact" class="button">Nouveau message</a>
            </div>
        <?php else : ?>
            <form action="index.php?page=contact&task=send" method="post" id="form-contact" data-page="contact" data-task="send" class="form box-container">
                <fieldset>
                    <label for="contact-firstname">Prénom</label>
                    <input type="text" id="contact-firstname" name="firstname" data-type="text" value="<?= $session !== null ? $session['firstname'] : '' ?>" required>

                    <label for="contact-lastname">Nom</label>
                    <input type="text" id="contact-lastname" name="lastname" data-type="text" value="<?= $session !== null ? $session['lastname'] : '' ?>" required>

                    <label for="contact-email">Email</label>
                    <input id="contact-email" type="email" name="email" data-type="email" value="<?= $session !== null ? $session['email'] : '' ?>" required>

                    <label for="contact-subject">Sujet</label>
                    <input type="text" id="contact-subject" name="subject" data-type="title" value="<?= \Libraries\Session::issetValue('contact', 'subject', '') ?>" required>

                    <label for="contact-message">Message</label>
                    <textarea id="contact-message" name="message" data-type="description" placeholder="Votre message" cols="30" rows="10" required><?= \Libraries\Session::issetValue('contact', 'message', '') ?></textarea>

                    <button type="submit">Envoyer</button>
                </fieldset>
            </form>
        <?php 
            unset($_SESSION['contact']);
            endif;
        ?>
    </div>
</section>