<section class="section-home disabled">
    <video autoplay loop muted preload="metadata" poster="assets/img/girl.jpg">
        <source src="assets/video/776180221.mp4" type="video/mp4">
    </video>


    <div class=" band">
        <svg class="triangle-top" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 20" enable-background="new 0 0 1280 20" xml:space="preserve" preserveAspectRatio="none">
            <polygon points="1280,20 0,20 0,0 " fill="rgba(var(--white), 0.3)" />
        </svg>
        <article>
            <h1>My Vietnam</h1>
            <p>Le Vietnam a tout pour vous charmer. La convivialité de ses habitants, sa nature surprenante et sa gastronomie extraordinaire vous feront vivre un voyage incroyable.</p>
            <p>Le Vietnam, c’est aussi des grandes villes où se mélange des buildings et des appartements minuscules collés les uns aux autres, des nuées de scooter dans les rues, des micros commerces pour acheter un jus d’orange ou un bánh bao, un endroit où on se sent vivant.</p>
            <p>Ce site fait un petit tour dans les différentes régions du Vietnam, toutes très différentes. On vous y présente également les plats les plus populaires, à absolument goûter au moins une fois dans sa vie.</p>
        </article>
        <svg class="triangle-bottom" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 20" enable-background="new 0 0 1280 20" xml:space="preserve" preserveAspectRatio="none">
            <polygon points="1280,20 0,0 1280,0 " fill="rgba(var(--white), 0.3)" />
        </svg>
    </div>
</section>