<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="projet-final">
    <!-- FAVICON -->
    <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon/favicon.png">
    <!-- NORMALIZE STYLE -->
    <link rel="stylesheet" href="assets/css/normalize.css">
    <!-- GOOGLE FONT -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;1,100;1,200;1,300;1,400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&family=WindSong&display=swap" rel="stylesheet">
    <!-- <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet"> -->
    <!-- FONT AWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- WEBISTE THEME -->
    <link rel="stylesheet" href="assets/css/theme.css">
    <noscript>
        <link rel="stylesheet" href="assets/css/noscript.css">
    </noscript>
    <!-- TITLE -->
    <title>My Vietnam - <?= $pageTitle ?></title>
</head>

<body>
    <header>
        <?php include '../router/header.php' ?>
        <?php include 'widget.phtml' ?>
    </header>
    <main>
        <?php include $pageContent ?>
    </main>
    <?php include 'footer.phtml' ?>
    <!-- SCRIPTS -->
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <?php if (isset($_GET['page']) && $_GET['page'] === "dish") : ?>
        <!-- MIXITUP SCRIPT -->
        <script src="assets/js/mixitup/dist/mixitup.min.js"></script>
        <script>
            let mixer = mixitup(".mixitup");
        </script>
    <?php endif ?>
    <!-- SCRIPT MODULE -->
    <script type="module" src="assets/js/app.js"></script>
</body>

</html>