<section class="section-thanks">
    <h1>Remerciements</h1>
    <div class="container">
        <article>
            <h2>Merci à</h2>
             <p><span>Thu Hà</span>, pour tes connaissances du Vietnam qui m'ont permis de réaliser ce site</p>
                <p>Mes profs <span>Yvon</span> et <span>François</span>, vos cours étaient top</p>
                <p>es mentors durant la réalisation de ce projet, <span>Pascal</span>, <span>Charlène</span> et <span>Adrien</span>, pour votre aide et vos conseils</p>
                <p><a href="https://www.youtube.com/channel/UCS71mal_TkTW_PpZR9YLpIA" target="_blank"><span>Lior Chamla</span></a> et <a href="https://grafikart.fr/" target="_blank"><span>Grafikart.fr</span></a> pour les nombreux cours en ligne très utiles</p>
                <p>Mes camarades du Live 53, nos échanges étaient une réelle motivation</p>
                <p>L'équipe de la <a href="https://3wa.fr/" target="_blank"><span>3W Academy</span></a> pour toute l'aide apportée durant ce bootcamp</p>
                <p>A tout mon entourage pour votre soutien</p>
            <a href="https://3wa.fr/" target="_blank" class="logo-3wa"><img src="https://3wa.fr/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2020/01/cropped-big.png.webp" alt="Logo de la 3D Academy"></a>
        </article>
    </div>
</section>