<nav>
    <ul class="paging">
        <li class="previous <?= ($currentPage == 1) ? "disabled" : "" ?>">
            <a href="<?= $url ?>&indexPage=<?= $currentPage - 1 ?>"><i class="fas fa-arrow-alt-circle-left"></i></a>
        </li>
        <?php for ($i = 1; $i <= $pageTotal; $i++) : ?>
            <?php if($i > $currentPage - 3 && $i < $currentPage + 3): ?>
            <li class="page-nav <?= ($currentPage == $i) ? "active" : "" ?>">
                <a href="<?= $url  ?>&indexPage=<?= $i ?>"><?= $i ?></a>
            </li>
            <?php endif ?>
        <?php endfor ?>
        <li class="next <?= ($currentPage == $pageTotal) ? "disabled" : "" ?>">
            <a href="<?= $url ?>&indexPage=<?= $currentPage + 1 ?>"><i class="fas fa-arrow-alt-circle-right"></i></a>
        </li>
    </ul>
</nav>