<section class="section-back">
    <h1>Users</h1>
    <div class="container">
        <form action="index.php?page=back&task=updateUser" method="post" class="form-table box-container">
            <div class="table-overflow">
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Prénom</th>
                            <th>Nom</th>
                            <th>Email</th>
                            <th>User</th>
                            <th>Admin</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($users as $user) : ?>
                            <tr>
                                <td><?= $user['user_id'] ?></td>
                                <td><?= $user['firstname'] ?></td>
                                <td><?= $user['lastname'] ?></td>
                                <td><?= $user['email'] ?></td>
                                <?php if ($user['user_id'] !== $_SESSION['login']['user_id']) : ?>
                                    <td class="center">
                                        <input type="radio" name="is-admin[<?= $user['user_id'] ?>]" value=0 <?= $user['is_admin'] === '0' ? 'checked' : '' ?>>
                                    </td>
                                    <td class="center">
                                        <input type="radio" name="is-admin[<?= $user['user_id'] ?>]" value=1 <?= $user['is_admin'] === '1' ? 'checked' : '' ?>>
                                    </td>
                                    <td class="center"><a href="index.php?page=back&task=deleteUser&id=<?= $user['user_id'] ?>">Supprimer</a></td>
                                <?php else : ?>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                <?php endif ?>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
            <button type="submit">Valider</button>
        </form>
    </div>
</section>