<section class="section-back">
    <h1>Modifier le produit</h1>
    <div class="container">
        <?php \Libraries\Error::display('error-product') ?>
        <form action="index.php?page=back&task=manageProduct" method="post" enctype="multipart/form-data" class="box-container">
            <fieldset>
                <input type="hidden" name="id" value=<?= $_SESSION['back']['id'] ?>>

                <label for="name">Nom</label>
                <input type="text" name="name" value="<?= $session['name'] ?>" id="name" required>

                <label for="description">Description</label>
                <textarea name="description" id="description" rows="10" required><?= $session['description'] ?></textarea>

                <label for="picture">Image</label>
                <input type="file" name="picture" id="picture">


                <label aria-labelledby="actual-picture">Image actuelle</label>
                <input type="hidden" name="current-picture" value="<?= $session['picture'] ?>" id="current-picture">
                <p id="actual-picture"><?= $session['picture'] ?></p>

                <label for="price">Prix</label>
                <input type="text" name="price" value="<?= $session['price'] ?>" id="price" required>

                <label for="stock">Stock</label>
                <input type="text" name="stock" value="<?= $session['stock'] ?>" id="stock" required>

                <label for="product-category">Catégorie</label>
                <select name="category" id="product-category" class="select">
                    <option value="vêtement" <?= $session['category'] === "vêtement" ? 'selected' : '' ?>>Vêtement</option>
                    <option value="épicerie" <?= $session['category'] === "épicerie" ? 'selected' : '' ?>>Épicerie</option>
                    <option value="goodies" <?= $session['category'] === "goodies" ? 'selected' : '' ?>>Goodies</option>
                </select>

                <div class="group-buttons">
                    <button type="submit" name="update" class="outline">Modifier</button>
                    <button type="submit" name="delete" class="delete">Supprimer</button>
                    <a href="index.php?page=back&task=backShop" class="cancel">Annuler</a>
                </div>
            </fieldset>
        </form>
        <?php unset($_SESSION['back-product']); ?>
    </div>
</section>